### ISSUE TITLE
Can I use your contents?

### ISSUE THREAD

**Issue by szaghi** [cmacmackin/fortran-tutorial#1]
@cmacmackin 

Dear Chris, in the near future it could happen (hopefully for me not...) that I have to _teach_ to a small set of my colleagues some of the new features of modern Fortran standards (2003+). Your contents could be very useful for me (indeed I am not able to see the final output of your contents). Can I use your contents?

In the (unfortunate) case I will have to do such lectures I will share my slides too and I will explicitly cite your copyright.

Cheers,
Stefano

**Comment by cmacmackin** [comment]
You are, of course, welcome to use this tutorial. I'm afraid that what 
you see in this repository is really all of the content I have. I never 
prepared any slides, but just displayed my text editor to the group 
(using a large font). I don't know if it will be of any use to you, but 
a nicely rendered (and slightly updated) version of the tutorial is 
available on my professional website: 
https://cmacmackin.github.io/pages/fortran-tutorial.html. One issue I do 
have with this tutorial is the fact that it doesn't teach any object 
oriented programming. This was for reasons of brevity, but I should 
probably add a section on OOP at some point.

On 25/05/16 09:11, Stefano Zaghi wrote:

> @cmacmackin https://github.com/cmacmackin
> 
> Dear Chris, in the near future it could happen (hopefully for me 
> not...) that I have to /teach/ to a small set of my colleagues some of 
> the new features of modern Fortran standards (2003+). Your contents 
> could be very useful for me (indeed I am not able to see the final 
> output of your contents). Can I use your contents?
> 
> In the (unfortunate) case I will have to do such lectures I will share 
> my slides too and I will explicitly cite your copyright.
> 
> Cheers,
> Stefano
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/cmacmackin/fortran-tutorial/issues/1

## 

Chris MacMackin
cmacmackin.github.io http://cmacmackin.github.io

**Comment by szaghi** [comment]
@cmacmackin Thank you very much. The contents are good as a basis, what I did not find was a _nicely_ rendered version... I read your blog every day during my breakfast, but I forget this post :smile: 

Thank you again, I will let you know if have to do these lectures and I will share my contents in case.

Cheers.

**Comment by cmacmackin** [comment]
Well, that post is, strictly speaking, a 'page', so it wouldn't show up 
in the RSS feed. Incidentally, my old blog (with the politics) isn't 
actually gone--I just moved it so as to thoroughly separate it from my 
professional life. You can find it at 
`http://politicalphysicist.github.io/`.

On 25/05/16 09:25, Stefano Zaghi wrote:
>
> @cmacmackin <https://github.com/cmacmackin> Thank you very much. The 
> contents are good as a basis, what I did not find was a /nicely/ 
> rendered version... I read your blog every day during my breakfast, 
> but I forget this post 😄
>
> Thank you again, I will let you know if have to do these lectures and 
> I will share my contents in case.
>
> Cheers.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cmacmackin/fortran-tutorial/issues/1#issuecomment-221506274>
>

-- 
Chris MacMackin
cmacmackin.github.io <http://cmacmackin.github.io>

**Comment by szaghi** [comment]
Wise approach to separate politics contents from the professional ones, my compliments!

**Comment by szaghi** [comment]
@cmacmackin 

@alexpacheco 

Dear Chris,

I start to write my talk, http://szaghi.github.io/zen-of-fortran-talk/#/slide-0

I have currently not used many of your contents, but I wil do.

> Java script must work on your browser to correctly read the Talk.

At the current last slide I cited your work http://szaghi.github.io/zen-of-fortran-talk/#/slide-35

I hope this is ok for you.

Cheers.

**Comment by cmacmackin** [comment]
Sounds good.
